version: "3.1"

services:
  db:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: catdog
    ports:
      - "3306:3306"
    volumes:
      - ./data:/var/lib/mysql
      - ./initdb:/docker-entrypoint-initdb.d
    restart: always

  # app:
  #   build: .
  #   ports:
  #     - "8080:8080"
  #   depends_on:
  #     - db
