-- MySQL Script generated by MySQL Workbench
-- Thu Jan  4 01:51:20 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema catdog
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema catdog
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `catdog` DEFAULT CHARACTER SET utf8 ;
USE `catdog` ;

-- -----------------------------------------------------
-- Table `catdog`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `catdog`.`user` (
  `user_id` VARCHAR(45) NOT NULL,
  `user_pw` VARCHAR(100) NOT NULL,
  `user_name` VARCHAR(45) NOT NULL,
  `user_phoneNumber` VARCHAR(45) NULL,
  `user_regDate` DATETIME NULL,
  `user_image` VARCHAR(100) NULL,
  `user_matchinguse` TINYINT(1) NULL,
  PRIMARY KEY (`user_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `catdog`.`order`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `catdog`.`order` (
  `order_no` INT NOT NULL AUTO_INCREMENT,
  `user_user_id` VARCHAR(45) NOT NULL,
  `order_price` INT NOT NULL,
  `order_date` DATETIME NOT NULL,
  INDEX `fk_order_user_idx` (`user_user_id` ASC) VISIBLE,
  PRIMARY KEY (`order_no`),
  CONSTRAINT `fk_order_user`
    FOREIGN KEY (`user_user_id`)
    REFERENCES `catdog`.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `catdog`.`matching`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `catdog`.`matching` (
  `matching_no` INT NOT NULL AUTO_INCREMENT,
  `user_user_id` VARCHAR(45) NOT NULL,
  `matching_user_id` VARCHAR(45) NOT NULL,
  `matching_request` INT NOT NULL,
  `matching_response` INT NOT NULL,
  `matching_result` TINYINT(1) NULL,
  PRIMARY KEY (`matching_no`),
  INDEX `fk_matching_user1_idx` (`user_user_id` ASC) VISIBLE,
  CONSTRAINT `fk_matching_user1`
    FOREIGN KEY (`user_user_id`)
    REFERENCES `catdog`.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `catdog`.`category1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `catdog`.`category1` (
  `category1_no` INT NOT NULL AUTO_INCREMENT,
  `category1_type` VARCHAR(45) NULL,
  PRIMARY KEY (`category1_no`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `catdog`.`category2`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `catdog`.`category2` (
  `category2_no` INT NOT NULL AUTO_INCREMENT,
  `category2_type` VARCHAR(45) NULL,
  PRIMARY KEY (`category2_no`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `catdog`.`community`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `catdog`.`community` (
  `community_no` INT NOT NULL AUTO_INCREMENT,
  `user_user_id` VARCHAR(45) NOT NULL,
  `category_no` INT NOT NULL,
  `community_content` VARCHAR(2000) NOT NULL,
  `community_regdate` DATETIME NOT NULL,
  `community_editdate` DATETIME NULL,
  PRIMARY KEY (`community_no`),
  INDEX `fk_community_user1_idx` (`user_user_id` ASC) VISIBLE,
  INDEX `fk_community_category11_idx` (`category_no` ASC) VISIBLE,
  CONSTRAINT `fk_community_user1`
    FOREIGN KEY (`user_user_id`)
    REFERENCES `catdog`.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_community_category11`
    FOREIGN KEY (`category_no`)
    REFERENCES `catdog`.`category1` (`category1_no`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `catdog`.`heart`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `catdog`.`heart` (
  `heart_no` INT NOT NULL AUTO_INCREMENT,
  `community_no` INT NOT NULL,
  `user_id` VARCHAR(45) NOT NULL,
  `heart_boolean` TINYINT(1) NOT NULL,
  PRIMARY KEY (`heart_no`),
  INDEX `fk_heart_community1_idx` (`community_no` ASC) VISIBLE,
  INDEX `fk_heart_user1_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_heart_community1`
    FOREIGN KEY (`community_no`)
    REFERENCES `catdog`.`community` (`community_no`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_heart_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `catdog`.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `catdog`.`reply`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `catdog`.`reply` (
  `reply_no` INT NOT NULL AUTO_INCREMENT,
  `community_no` INT NOT NULL,
  `user_id` VARCHAR(45) NOT NULL,
  `reply_content` VARCHAR(500) NOT NULL,
  `reply_regdate` DATETIME NOT NULL,
  PRIMARY KEY (`reply_no`),
  INDEX `fk_reply_community1_idx` (`community_no` ASC) VISIBLE,
  INDEX `fk_reply_user1_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_reply_community1`
    FOREIGN KEY (`community_no`)
    REFERENCES `catdog`.`community` (`community_no`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_reply_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `catdog`.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `catdog`.`pet`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `catdog`.`pet` (
  `pet_no` INT NOT NULL AUTO_INCREMENT,
  `user_id` VARCHAR(45) NOT NULL,
  `category1_no` INT NULL,
  `category2_no` INT NULL,
  `pet_name` VARCHAR(45) NULL,
  `pet_age` INT NULL,
  `pet_animalnum` BIGINT(20) NULL,
  `pet_gender` INT NULL,
  PRIMARY KEY (`pet_no`),
  INDEX `fk_pet_user1_idx` (`user_id` ASC) VISIBLE,
  INDEX `fk_pet_category11_idx` (`category1_no` ASC) VISIBLE,
  INDEX `fk_pet_category21_idx` (`category2_no` ASC) VISIBLE,
  CONSTRAINT `fk_pet_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `catdog`.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pet_category11`
    FOREIGN KEY (`category1_no`)
    REFERENCES `catdog`.`category1` (`category1_no`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pet_category21`
    FOREIGN KEY (`category2_no`)
    REFERENCES `catdog`.`category2` (`category2_no`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `catdog`.`product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `catdog`.`product` (
  `product_no` INT NOT NULL AUTO_INCREMENT,
  `user_id` VARCHAR(45) NOT NULL,
  `category1_no` INT NULL,
  `product_name` VARCHAR(45) NULL,
  `product_stock` INT NULL,
  `product_content` VARCHAR(500) NULL,
  `product_price` INT NULL,
  `product_regdate` DATETIME NULL,
  `product_soldQuantity` INT NULL,
  PRIMARY KEY (`product_no`),
  INDEX `fk_product_user1_idx` (`user_id` ASC) VISIBLE,
  INDEX `fk_product_category11_idx` (`category1_no` ASC) VISIBLE,
  CONSTRAINT `fk_product_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `catdog`.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_product_category11`
    FOREIGN KEY (`category1_no`)
    REFERENCES `catdog`.`category1` (`category1_no`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `catdog`.`cart`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `catdog`.`cart` (
  `cart_no` INT NOT NULL AUTO_INCREMENT,
  `user_id` VARCHAR(45) NULL,
  `product_no` INT NULL,
  `cart_quantity` INT NULL,
  PRIMARY KEY (`cart_no`),
  INDEX `fk_cart_product1_idx` (`product_no` ASC) VISIBLE,
  INDEX `fk_cart_user1_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_cart_product1`
    FOREIGN KEY (`product_no`)
    REFERENCES `catdog`.`product` (`product_no`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cart_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `catdog`.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `catdog`.`review`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `catdog`.`review` (
  `review_no` INT NOT NULL AUTO_INCREMENT,
  `user_id` VARCHAR(45) NOT NULL,
  `product_no` INT NOT NULL,
  `review_regdate` DATETIME NULL,
  `review_score` INT NULL,
  `review_content` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`review_no`),
  INDEX `fk_review_user1_idx` (`user_id` ASC) VISIBLE,
  INDEX `fk_review_product1_idx` (`product_no` ASC) VISIBLE,
  CONSTRAINT `fk_review_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `catdog`.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_review_product1`
    FOREIGN KEY (`product_no`)
    REFERENCES `catdog`.`product` (`product_no`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `catdog`.`hospital`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `catdog`.`hospital` (
  `hospital_id` INT NOT NULL AUTO_INCREMENT,
  `address_name` VARCHAR(45) NULL,
  `phone` VARCHAR(45) NULL,
  `place_name` VARCHAR(45) NULL,
  `place_url` VARCHAR(45) NULL,
  `road_address_name` VARCHAR(45) NULL,
  `longitude` DOUBLE NULL,
  `latitude` DOUBLE NULL,
  PRIMARY KEY (`hospital_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `catdog`.`board`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `catdog`.`board` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `writer` VARCHAR(45) NOT NULL,
  `content` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
